
  version: '3.8'

  services:
   mongo:
    image: mongo
    container_name: mongodb
    ports:
     - "27017:27017"

   mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
     - "8081:8081"
    links:
     - mongo
    environment:
     - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017